### PR TITLE
some edits to the text and some formatting

### PR DESCRIPTION
**Pull request by ilonamm**
Changed the texts a bit based on feedback, and did some light styling...

### CODE REVIEW

**Comment by ilonamm** [comment]
To my eye the fonts in the demo look slightly different than the one in beta, even though they should be exactly the same (there's still a bit of positioning and line fixing todo).
From demo (readymag):
image

From localhost:
image

It's like the character spacing is a bit wider in demo, however didn't find it inspecting the code and the font itself.

**Comment by ilonamm** [comment]
added alphabethical ordering of the autoselect brands, but needs further work - now it sorts first uppercase, then lowercase..

**Comment by ilonamm** [comment]
@batmany13 could you review&approve these on Mon, could start testing with this instead of the demo :) (unless @ohanhi feels like reviewing code on his holiday :)

**Comment by ilonamm** [comment]
[Landing page - minor styling & footer](https://trello.com/c/f0zWNyV6/39-landing-page-minor-styling-footer)

**Review by batmany13 — APPROVED** [review]

**Comment by ilonamm** [comment]
#15

**Pull request merged**
