### PR TITLE
fixing comma issue

### PR DESCRIPTION
**Pull request by ilonamm**
refs #6

### CODE REVIEW

**Review by batmany13 — APPROVED** [review]
👍

**Comment by batmany13** [comment]
@ilonamm i added the issue its referencing

**Comment by ilonamm** [comment]
[Set up github + circleCI + Heroku](https://trello.com/c/Dcd4hT9i/3-set-up-github-circleci-heroku)

**Comment by ilonamm** [comment]
[Set up github + circleCI + Heroku](https://trello.com/c/Dcd4hT9i/3-set-up-github-circleci-heroku)

**Pull request merged**
